name: lint

on: push

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.4'
            - name: Install
              run: make install
            - name: phpcs lint
              run: make lint
